sudo: required
language: python
python:
  - "2.7"

services:
  - docker

before_install:
- docker pull caladreas/mkdocs-docker-build-container
- docker run -d --name buildcont -v ${TRAVIS_BUILD_DIR}:/usr/src/app caladreas/mkdocs-docker-build-container /bin/sh -c "mkdocs build"
- docker logs buildcont

script: pytest -h
