sudo: required
language: python
python:
- '2.7'
services:
- docker
before_install:
- docker pull caladreas/mkdocs-docker-build-container
- docker run -d --name buildcont -v ${TRAVIS_BUILD_DIR}:/usr/src/app caladreas/mkdocs-docker-build-container
  /bin/sh -c "mkdocs build"
- docker logs buildcont
script: pytest -h

deploy:
  provider: s3
  access_key_id: AKIAI6VTWJPMRF26WVDA
  secret_access_key:
    secure: PnJda1cqiobcw7WO0l5JOXS1F030gKjVfWHVMvnhUijvy4Sg6sghxWTVrfW8TgRfra7ELMw2b0do6KsFBn33XrrYlkRD7ccWx9YQgxePuA9mSTYT42DsA+fZ6Dc0SeWGb+XyvWf+vhBCz9ui+sPllZdsZbCl00FOtY4pLchl6hRoGC05uuxkOcrFsCSvzy8czS5OeBl8Ls1LL3bKvodKFlRM2YiRTqlErRUuvLa/XaCGuVAFvpyDfqoy8d9PBmSDAbNMQSLPCjLBlAinXBqQB6NpQqrinyjra1NmfT5eWjO95WHXnD00Cx/c1MznlQvDm7kRguPb+ztaL9QkqhBpA1sU6+tnyjF5ZsseealiCQu8PJSve8xlAT435XZbHoRtjGBlUhqqQJULQnKKIpk4ZKoAOSgXnmqM1TlbdIV4NOfNCSbgHEmdZiPokCXWSVL9ZOCbkU6WE+AKXVX0/g8pFgvGdCCJuSuGKKnwKgprG8M4zKQX9CbMhpo9XlJVemV42NGYGpDAi2b/kHnUHwshxTYaBH97ueicZGZw1uzQtZa+UWA/OD3aPMQxg8IZU/8hb2325cZ2TZKvejVwREP+Uh/EDZGNduzfGUj4sAKgp6JpGKpqNr+mKtE3rsOzg7QNlFT/1Olg599jUkavG791DB6nplxjNvxcrN9JaoH+ZpA=
  bucket: kearos
  local-dir: site
  acl: public_read
  on:
    repo: joostvdg/kearos-blog
