# Meta
site_name: Kearos
ite_author: 'Joost van der Griendt'
site_url: 'https://joostvdg.github.io/'

# Copyright
copyright: 'Copyright &copy; 2017 Joost van der Griendt'

pages:
- Home: index.md
- About Site: kearos.md
- About Me: moi.md

# Theme
theme: 'material'

# Extra Options
extra:
  palette:
    primary: 'blue grey'
    accent: 'teal'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

extra:
  social:
    - type: 'github'
      link: 'https://github.com/joostvdg'
    - type: 'twitter'
      link: 'https://twitter.com/joost_vdg'
    - type: 'linkedin'
      link: 'https://nl.linkedin.com/in/joostvdg'
